refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      # https://docs.rs/log4rs/1.2.0/log4rs/encode/pattern/index.html
      # https://docs.rs/chrono/0.4.23/chrono/format/strftime/index.html
      pattern: "{d(%Y-%m-%d %H:%M:%S.%3f %Z)(utc)} [{l}] - {T} - {M}:{L} - {m}{n}"

root:
  level: info
  appenders:
    - stdout
